onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /romeosweep_test/ACLK
add wave -noupdate /romeosweep_test/ACS
add wave -noupdate /romeosweep_test/ACST
add wave -noupdate /romeosweep_test/ENDPOINTSTEP
add wave -noupdate /romeosweep_test/LDCLK
add wave -noupdate /romeosweep_test/LDCS
add wave -noupdate /romeosweep_test/LDSDI
add wave -noupdate /romeosweep_test/SET
add wave -noupdate /romeosweep_test/exp_SC_packet
add wave -noupdate /romeosweep_test/exp_new_data
add wave -noupdate /romeosweep_test/ACLK_net_0
add wave -noupdate /romeosweep_test/ACS_net_0
add wave -noupdate /romeosweep_test/ACST_net_0
add wave -noupdate /romeosweep_test/CLK_GEN_0_CLK
add wave -noupdate /romeosweep_test/CLK_GEN_1_CLK
add wave -noupdate /romeosweep_test/DAC2
add wave -noupdate /romeosweep_test/ENDPOINTSTEP_net_0
add wave -noupdate /romeosweep_test/exp_new_data_net_0
add wave -noupdate /romeosweep_test/exp_SC_packet_net_0
add wave -noupdate /romeosweep_test/LDCLK_net_0
add wave -noupdate /romeosweep_test/LDCS_net_0
add wave -noupdate /romeosweep_test/LDSDI_net_0
add wave -noupdate /romeosweep_test/RESET_GEN_0_RESET
add wave -noupdate /romeosweep_test/SET_net_0
add wave -noupdate /romeosweep_test/SWEEP_SPIDER2_0_ADC_EN
add wave -noupdate /romeosweep_test/SWEEP_SPIDER2_0_DAC1
add wave -noupdate /romeosweep_test/SWEEP_SPIDER2_0_RADDR
add wave -noupdate /romeosweep_test/SWEEP_SPIDER2_0_REN0
add wave -noupdate /romeosweep_test/SWEEP_SPIDER2_0_REN1
add wave -noupdate /romeosweep_test/SWEEP_SPIDER2_0_SW_END
add wave -noupdate /romeosweep_test/SweepTable_0_RD
add wave -noupdate /romeosweep_test/SweepTable_1_RD
add wave -noupdate /romeosweep_test/LDCS_net_1
add wave -noupdate /romeosweep_test/LDSDI_net_1
add wave -noupdate /romeosweep_test/LDCLK_net_1
add wave -noupdate /romeosweep_test/ACS_net_1
add wave -noupdate /romeosweep_test/ACLK_net_1
add wave -noupdate /romeosweep_test/ACST_net_1
add wave -noupdate /romeosweep_test/exp_new_data_net_1
add wave -noupdate /romeosweep_test/exp_SC_packet_net_1
add wave -noupdate /romeosweep_test/SET_net_1
add wave -noupdate /romeosweep_test/ENDPOINTSTEP_net_1
add wave -noupdate /romeosweep_test/VCC_net
add wave -noupdate /romeosweep_test/GND_net
add wave -noupdate /romeosweep_test/N_SAMPLES_POINT_const_net_0
add wave -noupdate /romeosweep_test/N_POINT_STEP_const_net_0
add wave -noupdate /romeosweep_test/milliseconds_const_net_0
add wave -noupdate /romeosweep_test/N_STEPS_const_net_0
add wave -noupdate /romeosweep_test/N_SAMPLES_const_net_0
add wave -noupdate /romeosweep_test/N_SKIP_SAMPLES_const_net_0
add wave -noupdate /romeosweep_test/CBIASV0_const_net_0
add wave -noupdate /romeosweep_test/CBIASV1_const_net_0
add wave -noupdate /romeosweep_test/WD_const_net_0
add wave -noupdate /romeosweep_test/WADDR_const_net_0
add wave -noupdate /romeosweep_test/WD_const_net_1
add wave -noupdate /romeosweep_test/WADDR_const_net_1
add wave -noupdate /romeosweep_test/SW_END_OUT_PRE_INV0_0
add wave -noupdate /romeosweep_test/ACS
add wave -noupdate /romeosweep_test/ACST
add wave -noupdate /romeosweep_test/LDCLK
add wave -noupdate /romeosweep_test/exp_new_data
add wave -noupdate /romeosweep_test/ACLK_net_0
add wave -noupdate /romeosweep_test/ACS_net_0
add wave -noupdate /romeosweep_test/ACST_net_0
add wave -noupdate /romeosweep_test/CLK_GEN_0_CLK
add wave -noupdate /romeosweep_test/CLK_GEN_1_CLK
add wave -noupdate /romeosweep_test/exp_SC_packet_net_0
add wave -noupdate /romeosweep_test/LDCLK_net_0
add wave -noupdate /romeosweep_test/LDCS_net_0
add wave -noupdate /romeosweep_test/LDSDI_net_0
add wave -noupdate /romeosweep_test/RESET_GEN_0_RESET
add wave -noupdate /romeosweep_test/SET_net_0
add wave -noupdate /romeosweep_test/SWEEP_SPIDER2_0_DAC1
add wave -noupdate /romeosweep_test/SWEEP_SPIDER2_0_REN0
add wave -noupdate /romeosweep_test/SWEEP_SPIDER2_0_REN1
add wave -noupdate /romeosweep_test/SweepTable_0_RD
add wave -noupdate /romeosweep_test/SweepTable_1_RD
add wave -noupdate /romeosweep_test/LDSDI_net_1
add wave -noupdate /romeosweep_test/LDCLK_net_1
add wave -noupdate /romeosweep_test/ACS_net_1
add wave -noupdate /romeosweep_test/ACLK_net_1
add wave -noupdate /romeosweep_test/ACST_net_1
add wave -noupdate /romeosweep_test/exp_new_data_net_1
add wave -noupdate /romeosweep_test/exp_SC_packet_net_1
add wave -noupdate /romeosweep_test/SET_net_1
add wave -noupdate /romeosweep_test/VCC_net
add wave -noupdate /romeosweep_test/LDCS_net_1
add wave -noupdate /romeosweep_test/GND_net
add wave -noupdate /romeosweep_test/milliseconds_const_net_0
add wave -noupdate /romeosweep_test/CBIASV0_const_net_0
add wave -noupdate /romeosweep_test/CBIASV1_const_net_0
add wave -noupdate /romeosweep_test/WD_const_net_0
add wave -noupdate /romeosweep_test/WADDR_const_net_0
add wave -noupdate /romeosweep_test/WD_const_net_1
add wave -noupdate /romeosweep_test/WADDR_const_net_1
TreeUpdate [SetDefaultTree]
quietly WaveActivateNextPane
add wave -noupdate /romeosweep_test/ACLK
add wave -noupdate /romeosweep_test/exp_new_data_net_0
add wave -noupdate /romeosweep_test/SWEEP_SPIDER2_0_ADC_EN
add wave -noupdate /romeosweep_test/exp_SC_packet
add wave -noupdate /romeosweep_test/DAC2
add wave -noupdate /romeosweep_test/LDCS
add wave -noupdate /romeosweep_test/LDSDI
add wave -noupdate /romeosweep_test/SET
add wave -noupdate /romeosweep_test/SWEEP_SPIDER2_0_RADDR
add wave -noupdate /romeosweep_test/SW_END_OUT_PRE_INV0_0
add wave -noupdate /romeosweep_test/N_SAMPLES_POINT_const_net_0
add wave -noupdate /romeosweep_test/N_POINT_STEP_const_net_0
add wave -noupdate /romeosweep_test/N_STEPS_const_net_0
add wave -noupdate /romeosweep_test/N_SKIP_SAMPLES_const_net_0
add wave -noupdate /romeosweep_test/N_SAMPLES_const_net_0
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1579162 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 233
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {4977171 ps}
